export function defaultRandoms() {
  return ["Naked Dungeon/Trial", "Arena Race", "Other Game"]
}

export default function addActivities() {
  return {
    "1. Soloable": ["Fishing", "Delves", "Questing", "Leveling", "Farming", "Maesltrom Arena", "Vateshran Hollows"],
    "2. Small Group": ["World Bosses", "Battlegrounds", "Public Dungeons", "Random Normal", "Random Vet", "Pledges", "DSA", "Blackrose Prison"],
    "3. Base Dungeons": [ 
      "Fungal Grotto I",
      "Fungal Grotto II",
      "Spindleclutch I",
      "Spindleclutch II",
      "The Banished Cells I",
      "The Banished Cells II",
      "Darkshade Caverns I",
      "Darkshade Caverns II",
      "Wayrest Sewers I",
      "Wayrest Sewers II",
      "Elden Hollow I",
      "Elden Hollow II",
      "Arx Corinium",
      "Crypt of Hearts I",
      "Crypt of Hearts II",
      "City of Ash I",
      "City of Ash II",
      "Direfrost Keep",
      "Volenfell",
      "Tempest Island",
      "Blessed Crucible",
      "Blackheart Haven",
      "Selene's Web",
      "Vaults of Madness",
    ],
    "4. DLC Dungeons": [
      "Imperial City Prison",
      "White-Gold Tower",
      "Cradle of Shadows",
      "Ruins of Mazzatun",
      "Bloodroot Forge",
      "Falkreath Hold",
      "Fang Lair",
      "Scalecaller",
      "March of Sacrifices",
      "Moon Hunter Keep",
      "Depths of Malatar",
      "Frostvault",
      "Lair of Maarselok",
      "Moongrave Fane",
      "Icereach",
      "Unhallowed Grave",
      "Castle Thorn",
      "Stone Garden",
      "Black Drake Villa",
      "The Cauldron",
      "Dread Cellar",
      "Red Petal Bastion",
    ],
    "5. Trials": [
      "Aetherian Archives",
      "Hel Ra CItadel",
      "Sanctum Ophidia",
      "Maw of Lorkaj",
      "Halls of Fabrications",
      "Asylum Sanctorium",
      "Cloudrest",
      "Sunspire",
      "Kyne's Aegis",
      "Rockgrove",
    ],
    "6. Large scale / PvP": ["Cyrodiil PvP", "Imperial City"],
    "7. Random Fun": defaultRandoms(),
  }
}